services:
  api:
    build: 
      context: .
      dockerfile: docker/Dockerfile
    container_name: travelers_api
    restart: unless-stopped
    command: ['fastapi', 'run', '/app/main.py', '--port', '8000']
    environment:
      - LD_LIBRARY_PATH=/opt/vc/lib
    ports:
      - '8765:8000'
    volumes:
      - ./src/app:/app
